main_app/urls.py
from django.urls import path
from . import views

urlpatterns = [
    path('', views.home, name='home'),
    path('about/', views.about, name='about'),
    path('seeds/', views.seeds_index, name='index'),
    path('seeds/<int:seed_id>/', views.seeds_detail, name='detail'),
    path('seeds/create/', views.SeedCreate.as_view(), name='seeds_create'),
    path('seeds/<int:pk>/update/', views.SeedUpdate.as_view(), name='seeds_update'),
    path('seeds/<int:pk>/delete/', views.SeedDelete.as_view(), name='seeds_delete'),
    path('seeds/<int:seed_id>/add_watering/', views.add_watering, name='add_watering'),
    path('seeds/<int:seed_id>/assoc_plot/<int:plot_id>/', views.assoc_plot, name='assoc_plot'),
    path('seeds/<int:seed_id>/unassoc_plot/<int:plot_id>/', views.unassoc_plot, name='unassoc_plot'),
    path('plots/', views.PlotList.as_view(), name='plots_index'),
    path('plots/<int:pk>/', views.PlotDetail.as_view(), name='plots_detail'),
    path('plots/create/', views.PlotCreate.as_view(), name='plots_create'),
    path('plots/<int:pk>/update/', views.PlotUpdate.as_view(), name='plots_update'),
    path('plots/<int:pk>/delete/', views.PlotDelete.as_view(), name='plots_delete'),
]

seedsower/urls.py
from django.contrib import admin
from django.urls import path, include

urlpatterns = [
    path('admin/', admin.site.urls),
    path('', include('main_app.urls')),
]

main_app/models.py
from django.db import models
from django.urls import reverse
from datetime import date
from django.utils.timezone import now

WATERED = (
    ('Y', 'YES'),
    ('N', 'NO')
)

class Plot(models.Model):
    name = models.CharField(max_length=50)
    zone = models.CharField(max_length=50)

    def __str__(self):
        return self.name

    def get_absolute_url(self):
        return reverse('plots_detail', kwargs={'pk': self.id})
        # Plots have a M:M related manager named seed_set

# Create your models here.
class Seed(models.Model):
    #first define the attributes/fields
    name = models.CharField(max_length=100)
    type = models.CharField(max_length=100)
    #django will create inputs for a form and
    #text filed will create a <text area> not reugular <input>
    description = models.TextField(max_length=250)
    season = models.CharField(max_length=100)
    date_planted = models.DateField('Date Planted', default=now)
    # add a M:M association between seeds and plots
    plots = models.ManyToManyField(Plot)

    def __str__(self):
        return f'{self.name} ({self.id})'

    def get_absolute_url(self):
        return reverse('detail', kwargs={'seed_id': self.id})

class Watering(models.Model):
    date = models.DateField()
    water = models.CharField('Watered?',
         max_length=1,
            choices=WATERED,
            default=WATERED[0][0]
         )

    seed = models.ForeignKey(Seed, on_delete=models.CASCADE)

    def __str__(self):
        # Nice method for obtaining the friendly value of a Field.choice
        return f"{self.get_water_display()} on {self.date}"

    class Meta:
        ordering = ['-date']

main_app/forms.py
from django.forms import ModelForm
from .models import Watering

class WateringForm(ModelForm):
  class Meta:
    model = Watering
    fields = ['date', 'water']

main_app/views.py
from django.shortcuts import render, redirect
from django.views.generic.edit import CreateView, UpdateView, DeleteView
from django.views.generic import ListView, DetailView
from .models import Seed, Plot
from .forms import WateringForm


# Create your views here.


# Define the home view
def home(request):
  return render(request, 'home.html')

def about(request):
  return render(request, 'about.html')

def seeds_index(request):
  seeds = Seed.objects.all()
  return render(request, 'seeds/index.html', { 'seeds': seeds })

def seeds_detail(request, seed_id):
  seed = Seed.objects.get(id=seed_id)
  id_list = seed.plots.all().values_list('id')
  plots_not_planted = Plot.objects.exclude(id__in=id_list)
  watering_form = WateringForm()
  return render(request, 'seeds/detail.html', { 
    'seed': seed, 
    'watering_form': watering_form,
    'plots': plots_not_planted
    })

def assoc_plot(request, seed_id, plot_id):
  # Note that you can pass a plot's id instead of the whole plot object
  Seed.objects.get(id=seed_id).plots.add(plot_id)
  return redirect('detail', seed_id=seed_id)

def unassoc_plot(request, seed_id, plot_id):
  # Note that you can pass a plot's id instead of the whole plot object
  Seed.objects.get(id=seed_id).plots.remove(plot_id)
  return redirect('detail', seed_id=seed_id)
  
class SeedCreate(CreateView):
  model = Seed
  fields = ['type', 'description', 'season', 'date_planted']

class SeedUpdate(UpdateView):
  model = Seed
  # Let's disallow the renaming of a Seed by excluding the name field!
  fields = ['type', 'description', 'season', 'date_planted']

class SeedDelete(DeleteView):
  model = Seed
  success_url = '/seeds/'

def add_watering(request, seed_id):
  # create a ModelForm instance using the data in request.POST
  form = WateringForm(request.POST)
  # validate the form
  if form.is_valid():
    # don't save the form to the db until it
    # has the seed_id assigned
    new_watering = form.save(commit=False)
    new_watering.seed_id = seed_id
    new_watering.save()
  return redirect('detail', seed_id=seed_id)

class PlotList(ListView):
  model = Plot
  # fields = ['name', 'zone']

class PlotDetail(DetailView):
  model = Plot
  fields = ['name', 'zone']

class PlotCreate(CreateView):
  model = Plot
  fields = ['name', 'zone']

class PlotUpdate(UpdateView):
  model = Plot
  fields = ['name', 'zone']

class PlotDelete(DeleteView):
  model = Plot
  success_url = '/plots/'

main_app/templates/about.html
<!DOCTYPE html>
<html lang="en">
<head>
  <meta charset="UTF-8">
  <meta name="viewport" content="width=device-width, initial-scale=1.0">
  <meta http-equiv="X-UA-Compatible" content="ie=edge">
  <title>Seed Sower</title>
</head>
<body>
    {% extends 'base.html' %}
    {% block content %}
    <h1>Welcome to Seed Sower</h1>
    <p class="tagline">Lifes a garden, sow what!</p>
    <hr>
    <img id="home-pic" class="responsive-img" src="https://i.imgur.com/hDW0B7E.jpg">
    <!-- <footer>All Rights Reserved, &copy; 2022 Seed Sower</footer> -->
    {% endblock %}
  </body>
    <footer>All Rights Reserved, &copy; 2022 Seed Sower</footer>
</body>
</html>

main_app/templates/base.html
{% load static %}

<!DOCTYPE html>
<html lang="en">
<head>
  <meta charset="UTF-8">
  <meta name="viewport" content="width=device-width, initial-scale=1.0">
  <meta http-equiv="X-UA-Compatible" content="ie=edge">
  <title>Seed Sower</title>
  <link rel="stylesheet" href="https://cdnjs.cloudflare.com/ajax/libs/materialize/1.0.0/css/materialize.min.css">
  <link rel="stylesheet" type="text/css" href="{% static 'css/style.css' %}">
  <link href="https://fonts.googleapis.com/css2?family=Chelsea+Market&family=Gloria+Hallelujah&family=Love+Ya+Like+A+Sister&display=swap" rel="stylesheet">
  <script src="https://cdnjs.cloudflare.com/ajax/libs/materialize/1.0.0/js/materialize.min.js"></script>
</head>
<body>
  <header class="navbar-fixed">
    <nav>
      <div class="nav-wrapper">
        <ul>
          <li><a href="{% url 'home' %}" class="left brand-logo">&nbsp;&nbsp;Seed Sower</a></li>
        </ul>
        <ul class="right">
          <li><a href="{% url 'about' %}">About</a></li>
          <li><a href="{% url 'plots_create' %}">Add a Plot</a></li>
          <li><a href="{% url 'plots_index' %}">View All Plots</a></li>
          <li><a href="{% url 'seeds_create' %}">Add a Seed</a></li>
          <li><a href="{% url 'index' %}">View All Seeds</a></li>
        </ul>
      </div>
    </nav>
  </header>
  <main class="container">
    {% block content %}
    {% endblock %}
  </main>
  <footer class="page-footer">
    <div class="right">All Rights Reserved, &copy; 2022 Seed Sower &nbsp;</div>
  </footer>
</body>
</html>

main_app/templates/home.html
{% extends 'base.html' %}
{% block content %}

<h1>Home</h1>
<!-- <img class="home-pic" src="https://i.imgur.com/ts58krP.jpg" alt="dam"> -->
{% endblock %}

main_app/templates/main_app/plot_confirm_delete.html
{% extends 'base.html' %}

{% block content %}
  <h1>Delete Plot</h1>

  <h4>Are you sure you want to delete <span class="teal-text">{{ object.name }}</span>?</h4>

  <form action="" method="POST">
    {% csrf_token %}
    <input type="submit" value="Yes - Delete!" class="btn">
    <a href="{% url 'plots_detail' object.id %}">Cancel</a>
  </form>
{% endblock %}

main_app/templates/main_app/plot_detail.html
{% extends 'base.html' %}
{% block content %}

<h1>Plot Details</h1>

<div class="row">
  <div class="col s6 col-offset-3">
    <div class="card">
      <div class="card-content">
        <span class="card-title">{{ plot.name }}</span>
        <p>Zone: {{ plot.zone }}</p>
      </div>
      <div class="card-action">
        <a href="{% url 'plots_update' plot.id %}">Edit</a>
        <a href="{% url 'plots_delete' plot.id %}">Delete</a>
      </div>
    </div>
  </div>
</div>
{% endblock %}

main_app/templates/main_app/plot_form.html
{% extends 'base.html' %}

{% block content %}
  {% if object %}
    <h1>Edit <span class="teal-text">{{object.name}}</span></h1>
  {% else %}
    <h1>Add Plot</h1>
  {% endif %}
  <!-- Leaving the action empty makes the form post to the same url used to display it -->
  <form action="" method="post">
    <!-- Django requires the following for security purposes -->
    {% csrf_token %}
    <table>
      <!-- Render the inputs inside of <tr>s & <td>s -->
      {{ form.as_table }}
    </table>
    <input type="submit" value="Submit!" class="btn" id="sub-btn">
  </form>
{% endblock %}

main_app/templates/main_app/plot_list.html
{% extends 'base.html' %}
{% block content %}

<h1>Plot List</h1>

{% for plot in plot_list %}
  <a href="{% url 'plots_detail' plot.id %}">
    <div class="card">
        <div class="card-content">
            <span class="card-title">{{ plot.name }}</span>
            <p>Zone: {{ plot.zone }}</p>
        </div>
    </div>
  </a>
{% endfor %}

{% endblock %}

main_app/templates/main_app/seed_confirm_delete.html
{% extends 'base.html' %}

{% block content %}
  <h1>Delete Seed</h1>

  <h4>Are you sure you want to delete <span class="teal-text">{{ seed.name }}</span>?</h4>

  <form action="" method="POST">
    {% csrf_token %}
    <input type="submit" value="Yes - Delete!" class="btn">
    <a href="{% url 'detail' seed.id %}" class="cncl">Cancel</a>
  </form>
{% endblock %}

main_app/templates/main_app/seed_form.html
{% extends 'base.html' %}

{% block content %}
<main class="container1">
{% if object %}
  <h1>Edit <span class="teal-text">{{seed.name}}</span></h1>
{% else %}
  <h1>Add Seed</h1>
{% endif %}  
  <!-- Leaving the action empty makes the form post to the same url used to display it -->
  <form action="" method="POST" class="sub-form">
    <!-- Django requires the following for security purposes -->
    {% csrf_token %}
    <table>
      <!-- Render the inputs inside of <tr>s & <td>s -->
      {{ form.as_table }}
    </table>
    <div class="sub-btn">
        <input type="submit" value="Submit!" class="btn">
    </div>
  </form>
</main>
<script>
    const dateEl = document.getElementById('id_date_planted');
    M.Datepicker.init(dateEl, {
        format: 'yyyy-mm-dd',
        defaultDate: new Date(),
        setDefaultDate: true,
        autoClose: true
    });

    const selectEl = document.getElementById('id_seed');
    M.FormSelect.init(selectEl);
</script>
{% endblock %}

main_app/templates/seeds/detail.html
{% extends 'base.html' %}
{% block content %}

<h1>Seed Details</h1>

<div class="row">
    <div class="col s6">
        <div class="card">
            <div class="card-content">
                <span class="card-title">{{ seed.name }}</span>
                <p>Type: {{ seed.type }}</p>
                <p>Description: {{ seed.description }}</p>
                <p>Season: {{ seed.season }}</p>
                <p>Date Planted: {{ seed.date_planted }}</p>
            </div>
                <div class="card-action">
                    <a href="{% url 'seeds_update' seed.id %}">Edit</a>
                    <a href="{% url 'seeds_delete' seed.id %}">Delete</a>
                </div>
        </div>
    </div>
    <div class="col s6">
        <form action="{% url 'add_watering' seed.id %}" method="POST">
            {% csrf_token %}
            {{ watering_form.as_p }}
            <input type="submit" class="btn" value="Add Watering">
          </form>      
        <table class="striped">
          <thead>
            <tr><th>Date</th><th>Watered</th></tr>
          </thead>
          <tbody>
            {% for watering in seed.watering_set.all %}
              <tr>
                <td>{{watering.date}}</td>
                <td>{{watering.get_water_display}}</td>
              </tr>
            {% endfor %}
          </tbody>
        </table>
      </div>   
      <hr>
        <div class="row">
        <div class="col s6">
            <h3>{{ seed.name }}'s Plots</h3>
            {% if seed.plots.count %}
            {% for plot in seed.plots.all %}
                <div class="card">
                <div class="card-content">
                    <span class="card-title">
                    <span>{{ plot.name }}</span>
                    <br>
                    <span class="plot-zone">( {{ plot.zone }} )</span>
                    </span>
                </div>
                <div class="card-action">
                    <form action="{% url 'unassoc_plot' seed.id plot.id %}" method="POST">
                      {% csrf_token %}
                      <button type="submit" class="btn">Remove</button>
                    </form>
                </div>
            </div>
            {% endfor %}
            {% else %}
            <h5>Not Planted yet :(</h5>
            {% endif %}
        </div>
        <div class="col s6">
            <h3>Available Plots</h3>
            {% if plots.count %}
              {% for plot in plots.all %}
                <div class="card">
                  <div class="card-content">
                    <span class="card-title">
                        <span>{{ plot.name }}</span>
                        <br>
                        <span class="plot-zone">( {{ plot.zone }} )</span>
                    </span>
                  </div>
                  <div class="card-action">
                    <form action="{% url 'assoc_plot' seed.id plot.id %}" method="POST">
                      {% csrf_token %}
                      <button type="submit" class="btn">Add</button>
                    </form>
                  </div>
                </div>
              {% endfor %}
            {% else %}
              <h5>{{seed.name}} Has been planted in all plots!</h5>
            {% endif %}
          </div>
</div>
<script>
    const dateEl = document.getElementById('id_date');
    M.Datepicker.init(dateEl, {
        format: 'yyyy-mm-dd',
        defaultDate: new Date(),
        setDefaultDate: true,
        autoClose: true
    });

    const selectEl = document.getElementById('id_water');
    M.FormSelect.init(selectEl);
</script>
{% endblock %}

main_app/templates/seeds/index.html
{% extends 'base.html' %}
{% block content %}

<h1>Seed List</h1>

{% for seed in seeds %}
  <div class="card">
    <a href="{% url 'detail' seed.id %}">
      <div class="card-content">
        <span class="card-title">{{ seed.name }}</span>
        <p>Type: {{ seed.type }}</p>
        <p>Description: {{ seed.description }}</p>
        <p>Season: {{ seed.season }}</p>
        <p>Date Planted: {{ seed.date_planted }}</p>
      </div>
    </a>
  </div>
{% endfor %}

{% endblock %}